name: tezal_version_two
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.0
  carousel_slider: ^2.1.0
  awesome_dialog: ^0.1.4
  photo_view: ^0.9.2
  email_validator: ^1.0.4
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.7+2
  first_time_screen: ^1.0.3
  intro_views_flutter: "^2.4.0"
  flappy_search_bar: ^1.7.2
  shimmer: ^1.1.1
  get_ip: ^0.4.0
  http: ^0.12.1
  device_info: ^0.4.2+4
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
